### ISSUE TITLE
scalafmt outputs code that scalameta can't parse

### ISSUE THREAD

**Issue by mberndt123** [scalameta/scalafmt#5217]
Hi

My configuration:
```
version = "3.10.7"
runner.dialect = scala3
```

When I run scalafmt via CLI like this: `scalafmt Test.scala`, given code like this:
```scala
val _ = a(
  b =
    c:
      d
    + e
)

```
Scalafmt formats code like this:
```scala
val _ = a(
  b = c:
    d
  + e
)
```

~~This doesn't compile with the Scala compiler (3.8.1). In the `+ e` line it says `')' expected but 'identifer' found`. I also cannot format the same file again with scalafmt, with a very similar error message:~~
Scalameta apparently can't parse this, because when I try to format it again, I get an error.
```
org.scalafmt.dynamic.exceptions.PositionExceptionImpl: /tmp/Sink.scala:4: error: [dialect scala3] `)` expected but `identifier` found
  + e
  ^: /tmp/Sink.scala
```

**Comment by mberndt123** [comment]
I found a bug and I took the time to simplify the code and reported it to the best of my abilities. Yes, I misidentified the source of the error message, and readily admitted my mistake when it was pointed out. I don't think I deserve the blame for your loss of karma.
