### ISSUE TITLE
Option to remove redundant braces should not result in Scala 3 code that does not compile

### ISSUE THREAD

**Issue by djneades** [scalameta/scalafmt#2426]
- **Version**: 3.0.0-RC1
- **Integration**: Sbt (via sbt-scalafmt 2.4.2)
- **Configuration**:
```
version = "3.0.0-RC1"
maxColumn = 80

runner.dialect = scala3
rewrite.rules = [RedundantBraces]
newlines.source = unfold
```

## Steps

Given code like this (which compiles with Scala 3.0.0-RC2):
```scala
def main(args: Array[String]): Unit =
  args foreach {
    println(_)
  }
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats the code like this:
```scala
def main(args: Array[String]): Unit = args foreach println(_)
```

This code does not compile with Scala 3.0.0-RC2:

```
sbt:test> run
[info] compiling 1 Scala source to C:\Git\Overload\target\scala-3.0.0-RC2\classes ...
[error] -- [E081] Type Error: C:\Git\Overload\src\main\scala\Main.scala:1:59 ---------
[error] 1 |def main(args: Array[String]): Unit = args foreach println(_)
[error]   |                                                           ^
[error]   |   Missing parameter type
[error]   |
[error]   |   I could not infer the type of the parameter _$1 of expanded function:
[error]   |   _$1 => args foreach println(_$1).
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed 16 Apr 2021, 22:05:36
```

## Expectation

Scalafmt should not rewrite code such that it no longer compiles.

## Notes

It is only the combination of both `rewrite.rules = [RedundantBraces]` and `newlines.source = unfold` that causes this problem.
