### ISSUE TITLE
Issue with RedundantBraces and v2.5.3 : illegal start of simple expression

### ISSUE THREAD

**Issue by YannMoisan** [scalameta/scalafmt#2012]
- **Configuration**:
```
version=2.5.3

rewrite.rules = [RedundantBraces]
```

## Steps

Given code like this:
```scala
object Issue {
  def f(): Int = ???

  try {} finally {
    val _ = f()
  }
}
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

I got an error

```
Issue.scala:6: error: illegal start of simple expression
```

## Workaround

Setting `rewrite.redundantBraces.generalExpressions` to `false` seems to fix.
(the default value has changed from `false` to `true` in 2.5.0)

## Notes

It seems to work with version 2.4.x and fail with 2.5.x

Here is another example that fails with the same error

```
object Issue2 {
  def f(): Int = ???
  def g : Int => Unit = _ => {val _ = f()}
}
```
